"""initial commit

Revision ID: 052b65b5bdc8
Revises: 
Create Date: 2024-08-17 21:27:05.484968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052b65b5bdc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('logged_in_counter', sa.Integer(), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
