"""merged exam tables into one

Revision ID: 2db030bbf0cf
Revises: 86d1d52e8d3d
Create Date: 2024-08-31 14:50:24.916924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2db030bbf0cf'
down_revision = '86d1d52e8d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('a_level_exams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a_level_exams',
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('exam_series', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('board', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('qualification', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('examination_code', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('base_subject', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('duration', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tier', mysql.VARCHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('examination_code'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
