"""empty message

Revision ID: 57c55bd41cd8
Revises: 2db030bbf0cf
Create Date: 2024-08-31 14:52:02.424448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57c55bd41cd8'
down_revision = '2db030bbf0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('exam_series', sa.String(length=20), nullable=True),
    sa.Column('board', sa.String(length=20), nullable=True),
    sa.Column('qualification', sa.String(length=30), nullable=True),
    sa.Column('examination_code', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('base_subject', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('tier', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('examination_code')
    )
    op.drop_table('gcse_exams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcse_exams',
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('exam_series', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('board', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('qualification', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('examination_code', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('base_subject', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('duration', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tier', mysql.VARCHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('examination_code'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('exams')
    # ### end Alembic commands ###
