"""updated level int to str

Revision ID: 7e4b692bc0b9
Revises: ea7923fc342e
Create Date: 2024-08-31 21:22:40.476489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e4b692bc0b9'
down_revision = 'ea7923fc342e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.String(length=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
