"""added a level table

Revision ID: 86d1d52e8d3d
Revises: 39ac2159a8e5
Create Date: 2024-08-31 10:14:11.859081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d1d52e8d3d'
down_revision = '39ac2159a8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a_level_exams',
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('exam_series', sa.String(length=20), nullable=True),
    sa.Column('board', sa.String(length=20), nullable=True),
    sa.Column('qualification', sa.String(length=30), nullable=True),
    sa.Column('examination_code', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('base_subject', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('tier', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('examination_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('a_level_exams')
    # ### end Alembic commands ###
