"""updated selected subjects

Revision ID: c39d541331a8
Revises: 54d24870d465
Create Date: 2024-08-22 12:32:34.771664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c39d541331a8'
down_revision = '54d24870d465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_subjects', sa.JSON(), nullable=True))
        batch_op.drop_column('subjects')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjects', mysql.JSON(), nullable=True))
        batch_op.drop_column('selected_subjects')

    # ### end Alembic commands ###
