"""initial migration

Revision ID: ceb3e4e26102
Revises: 
Create Date: 2025-05-31 13:23:19.699386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb3e4e26102'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('exam_series', sa.String(length=20), nullable=True),
    sa.Column('board', sa.String(length=20), nullable=True),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('examination_code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('base_subject', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('tier', sa.String(length=1), nullable=True),
    sa.Column('level', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('examination_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('logged_in_counter', sa.Integer(), nullable=False),
    sa.Column('selected_subjects', sa.JSON(), nullable=True),
    sa.Column('level', sa.String(length=2), nullable=True),
    sa.Column('exam_start_time_am', sa.String(length=10), nullable=True),
    sa.Column('exam_start_time_pm', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('exams')
    # ### end Alembic commands ###
