"""changed user qualification to level int

Revision ID: e1949197f800
Revises: ece16610978c
Create Date: 2024-08-31 15:14:50.222737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1949197f800'
down_revision = 'ece16610978c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.drop_column('qualification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('level')

    # ### end Alembic commands ###
