"""updated level int to str

Revision ID: ea7923fc342e
Revises: e1949197f800
Create Date: 2024-08-31 21:15:55.990983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea7923fc342e'
down_revision = 'e1949197f800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.String(length=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
